In [1]:
import numpy as np

<a name='1.1'></a>
### 1.1 - System of Linear Equations

Here is a **system of linear equations** (or **linear system**) with three equations and three unknown variables:


$$\begin{cases} 
4x_1-3x_2+x_3=-10, \\ 2x_1+x_2+3x_3=0, \\ -x_1+2x_2-5x_3=17, \end{cases}\tag{1}$$

**To solve** this system of linear equations means to find such values of the variables $x_1$, $x_2$, $x_3$, that all of its equations are simultaneously satisfied.

In [23]:
A = np.array([[4, -3, 1], [2, 1, 3], [-1, 2, -5]], dtype = np.dtype(float));

b = np.array([-10, 0, 17]);

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)

Matrix A:
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]

Array b:
[-10   0  17]


In [24]:
print(f"Shape A: {np.shape(A)}");
print(f"Shape B: {np.shape(b)}")

Shape A: (3, 3)
Shape B: (3,)


In [25]:
x = np.linalg.solve(A, b);

print(f"Solution: {x}");

Solution: [ 1.  4. -2.]


<a name='1.3'></a>
### 1.3 - Evaluating the Determinant of a Matrix

Matrix $A$ corresponding to the linear system $(1)$ is a **square matrix** - it has the same number of rows and columns. In the case of a square matrix it is possible to calculate its determinant - a real number that characterizes some properties of the matrix. A linear system containing three equations with three unknown variables will have one solution if and only if the matrix $A$ has a non-zero determinant.

Let's calculate the determinant using `np.linalg.det(A)` function:

In [26]:
d = np.linalg.det(A);

print(f"Det(A): {d}")

Det(A): -60.000000000000036


Non singular, 

<a name='1.4'></a>
### 1.4 - What happens if the system has no unique solution?

Let's explore what happens if we use `np.linalg.solve` in a system with no unique solution (no solution at all or infinitely many solutions).

Given another system of linear equations:

$$\begin{cases} 
x_1+x_2+x_3=2, \\ x_2-3x_3=1, \\ 2x_1+x_2+5x_3=0, \end{cases}\tag{2}$$

let's find the determinant of the corresponding matrix.

In [27]:
A_2 = np.array([[1, 1, 1], [0, 1, -3], [2, 1,5]], dtype = np.dtype(float));

b_2 = np.array([2, 1, 0], dtype = np.dtype(float));

print(f"System A: {A_2}");
print(f"System B: {b_2}");

print(f"Solution 2: {np.linalg.solve(A_2, b_2)}")

System A: [[ 1.  1.  1.]
 [ 0.  1. -3.]
 [ 2.  1.  5.]]
System B: [2. 1. 0.]


LinAlgError: Singular matrix

In [29]:
# Throws error because is singular

d = np.linalg.det(A_2);

print(f"Determinant: {d}");

Determinant: 0.0
